language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on
  - OPENSHIFT_VERSION=3.11.0
  - OPENSHIFT_COMMIT=0cbc58b
  - OPENSHIFT_BIN=openshift-origin-client-tools-v${OPENSHIFT_VERSION}-${OPENSHIFT_COMMIT}-linux-64bit
services:
  - docker

cache:
  directories:
  - $GOPATH/pkg
before_install:
  - mkdir -p $HOME/gopath/src/github.com/wildfly/wildfly-operator
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/wildfly/wildfly-operator
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/wildfly/wildfly-operator
  - mkdir -p $HOME/openshift
  - export OPENSHIFT_DIR=$HOME/openshift 
before_script:
  - cd $OPENSHIFT_DIR
  - $HOME/gopath/src/github.com/wildfly/wildfly-operator/build/run-openshift.sh

after_failure:
  - docker ps -a
  - for log in $(docker ps -qa | xargs); do docker logs --tail 500 $log; done

script:
  - cd $TRAVIS_BUILD_DIR
  - make image
  - make setup
  - make test-e2e-16 KUBECONFIG=$OPENSHIFT_DIR/openshift.local.clusterup/kube-apiserver/admin.kubeconfig
  - make test-e2e-17 KUBECONFIG=$OPENSHIFT_DIR/openshift.local.clusterup/kube-apiserver/admin.kubeconfig
