language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

services:
  - docker

cache:
  directories:
  - $GOPATH/pkg
before_install:
  - mkdir -p $HOME/gopath/src/github.com/wildfly/wildfly-operator
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/wildfly/wildfly-operator
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/wildfly/wildfly-operator
before_script:
  - ci/start-okd-4.0.0.sh

after_failure:
  - docker ps -a
  - for log in $(docker ps -qa | xargs); do docker logs --tail 500 $log; done

script:
  - make image
  - make setup
  - make test-e2e-16 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig
  - make test-e2e-17 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig
